node {
    stage('Preparation') {
        // Get some code from a GitHub repository
        git url: 'https://github.com/ZackMvP/pyinstaller-cicd'
    }

    stage('Build') {
        docker.image('python:3.12.1-alpine3.19').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            stash(name: 'compiled-results', includes: 'sources/*.py*')
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
        input message: 'Lanjutkan ke tahap Deploy?'
    }
    stage('Deploy'){
        sleep time: 1, unit: 'MINUTES'
    }
}